import type { PlayerBus, PlayerAction } from "./PlayerBus";
import { createPlayerRequestId } from "./PlayerBus";
import { PlaybackSession } from "./PlaybackSession";
import type { Track } from "../types";
import type { TrackLoader } from "./TrackLoader";
import type { StreamController } from "../Controller/StreamController";
import type { FilterController } from "../Controller/FilterController";
import type { PlaybackController } from "../Controller/PlaybackController";
import type { QueueController } from "../Controller/QueueController";
import type { AntiStuckController } from "../Controller/AntiStuckController";
import type { TransitionController } from "../Controller/TransitionController";
import type { PreloadController } from "../Controller/PreloadController";
export interface PlaybackOrchestratorOptions { trackLoader?:TrackLoader;streamController?:StreamController;filterController?:FilterController;playbackController?:PlaybackController;queueController?:QueueController;antiStuckController?:AntiStuckController;transitionController?:TransitionController;preloadController?:PreloadController; }
export class PlaybackOrchestrator {
 private session:PlaybackSession|null=null; private readonly detachAction:()=>void; private readonly detachTrackEnd:()=>void; private readonly detachQueries:Array<()=>void>=[];
 constructor(private readonly bus:PlayerBus,private readonly o:PlaybackOrchestratorOptions={}){this.detachAction=bus.onAction((a,c)=>this.handleAction(a,c.signal));this.detachTrackEnd=bus.subscribe("TRACK_END",event=>{const session=event.session;if(!session)return;if(session.status==="ended"||session.status==="stopped")return;if(!this.session||this.session.id!==session.id)return;void this.advanceAfterTrackEnd(session);});this.detachQueries.push(bus.registerQuery("currentTrack",()=>this.session?.track??this.o.queueController?.queue.currentTrack??null),bus.registerQuery("playerState",()=>this.session?.status??"idle"),bus.registerQuery("queue",()=>this.o.queueController?.snapshot()??[]),bus.registerQuery("playbackSession",()=>this.session?.snapshot()??null),bus.registerQuery("position",()=>this.session?.position??null),bus.registerQuery("volume",()=>this.o.playbackController?.volumeValue??100),bus.registerQuery("isPlaying",()=>this.session?.status==="playing"),bus.registerQuery("isPaused",()=>this.session?.status==="paused"));}
 get currentSession(){return this.session;} get transitionPolicy(){return this.o.transitionController;}
 dispose(){this.detachAction();this.detachTrackEnd();for(const d of this.detachQueries)d();this.session?.destroy();this.session=null;}
 private async handleAction(a:PlayerAction,s:AbortSignal){if(s.aborted)return;switch(a.type){case"PLAY":if(a.track)await this.start(a.track,s);break;case"PAUSE":if(this.o.playbackController?.pause()){this.session?.markPaused();this.publishState();}break;case"RESUME":if(this.o.playbackController?.resume()){this.session?.markPlaying();this.publishState();}break;case"SEEK":await this.seek(a.position,s);break;case"STOP":await this.stop(s);break;case"SKIP":await this.skip(s);break;case"SET_VOLUME":this.o.playbackController?.setVolume(a.volume);break;}}
 private async stop(s:AbortSignal){if(s.aborted)return;this.o.playbackController?.stop();this.o.antiStuckController?.clear(this.session??undefined);this.session?.markStopped();this.o.streamController?.abortCurrent();this.o.trackLoader?.cancelPreload();this.publishState();}
 private async skip(s:AbortSignal){if(s.aborted)return;const from=this.session?.track??null;this.o.playbackController?.stop();if(this.session){this.o.antiStuckController?.clear(this.session);this.session.markEnded();this.bus.event({type:"TRACK_END",session:this.session.snapshot()});}this.o.streamController?.abortCurrent();this.o.trackLoader?.cancelPreload();const next=this.o.queueController?.next(true);if(next)await this.start(next,s,from);}
 private async advanceAfterTrackEnd(snapshot:ReturnType<PlaybackSession["snapshot"]>){if(!this.session||this.session.id!==snapshot.id||this.session.status==="ended"||this.session.status==="stopped")return;const from=this.session.track;this.session.markEnded();this.o.antiStuckController?.clear(this.session);this.o.streamController?.abortCurrent();const next=this.o.queueController?.next();if(next){await this.start(next,new AbortController().signal,from);return;}this.publishState();}
 private async seek(position:number,s:AbortSignal){const x=this.session;if(!x||!x.track||s.aborted)return;const duration=x.track.duration>1000?x.track.duration:x.track.duration*1000;if(position<0||position>duration)return;if(this.o.filterController?.getFilterString()){try{await this.bus.request({type:"[Player]->[Resource]:refresh",requestId:createPlayerRequestId(),position},{signal:s,timeoutMs:30000});}catch{}return;}if(this.o.playbackController?.seek(position,x)){x.updatePosition(position);this.publishState();}}
 private async start(track:Track,s:AbortSignal,from:Track|null=null){if(s.aborted)return;this.o.playbackController?.stop();this.o.streamController?.abortCurrent();this.o.antiStuckController?.clear(this.session??undefined);this.o.trackLoader?.resetRecovery(this.session?.track??undefined);const hasPreload=this.o.trackLoader?.hasPreload(track)??false;if(!hasPreload)this.o.trackLoader?.cancelPreload();this.session?.destroy();const x=new PlaybackSession();this.session=x;x.begin(track);this.o.queueController?.queue.setCurrentTrack(track);this.bus.event({type:"TRACK_LOADING",session:x.snapshot()});if(!this.o.trackLoader||!this.o.streamController||!this.o.playbackController){this.bus.publish("playbackSessionCreated",x.snapshot());this.bus.publish("trackRequested",track,x);return;}try{const loaded=await this.o.trackLoader.loadWithRecovery(track,x);if(s.aborted||!this.session?.owns(x.id))return;this.bus.event({type:"TRACK_LOADED",session:x.snapshot()});if(loaded.stream.remote&&loaded.stream.handle){await loaded.stream.handle.play();this.bus.event({type:"TRACK_STARTED",session:x.snapshot()});return;}let streamInfo=loaded.stream;if(this.o.filterController?.getFilterString()){this.o.filterController.setSourceStreamType(streamInfo.type??"arbitrary");streamInfo=await this.o.filterController.applyFiltersAndSeek(streamInfo,-1);}if(s.aborted||!this.session?.owns(x.id))return;const active=await this.o.streamController.replace(streamInfo,x);if(s.aborted||!this.session?.owns(x.id))return;const resource=this.o.streamController.createResource(active.stream,loaded.track);x.setResource(resource);this.o.playbackController.play(resource,x,from,loaded.track);x.markPlaying();this.bus.event({type:"TRACK_STARTED",session:x.snapshot()});await this.requestPreload(loaded.track,s);}catch(error){if(!x.signal.aborted&&!s.aborted)this.bus.event({type:"TRACK_ERROR",session:x.snapshot(),error:error instanceof Error?error:new Error(String(error))});}}
 private async requestPreload(track:Track,s:AbortSignal){if(!this.o.preloadController||s.aborted)return;try{await this.bus.request({type:"[Player]->[Preload]:request",requestId:createPlayerRequestId(),track},{signal:s,timeoutMs:30000});}catch{}}
 private publishState(){if(this.session)this.bus.publish("playbackStateChanged",this.session.snapshot());}
}
