import type { ConnectionController } from "../controller/ConnectionController";
import type { PlaybackController } from "../controller/PlaybackController";
import type { PreloadController } from "../controller/PreloadController";
import type { PreloadManager } from "../structures/PreloadManager";
import type { TrackLoader } from "../structures/TrackLoader";
import type { TrackResolver } from "../structures/TrackResolver";
import type { PlaybackOrchestrator } from "../structures/PlaybackOrchestrator";
import type { Bus } from "../structures/Bus";
import type { QueueController } from "../controller/QueueController";
import type { VolumeController } from "../controller/VolumeController";
import type { FilterController } from "../controller/FilterController";
import type { TransitionController } from "../controller/TransitionController";
import type { AntiStuckController } from "../controller/AntiStuckController";
import type { StreamController } from "../controller/StreamController";
import type { SaveController } from "../controller/SaveController";
import type { LifecycleController } from "../controller/LifecycleController";
import type { TTSController } from "../controller/TTSController";
import type { SearchController } from "../controller/SearchController";
import type { ForwardController } from "../controller/ForwardController";
import type { ResourceRefreshController } from "../controller/ResourceRefreshController";
import type { PlayerEventBridge } from "../controller/PlayerEventBridge";
import type { PluginController } from "../controller/PluginController";
import type { ExtensionController } from "../controller/ExtensionController";
import type { PlaybackSessionController } from "../controller/PlaybackSessionController";

export interface SharedControllerSet {
	connection: ConnectionController;
	playback: PlaybackController;
	preload: PreloadController;
	preloadManager: PreloadManager;
	trackLoader: TrackLoader;
	trackResolver: TrackResolver;
	orchestrator: PlaybackOrchestrator;
	bus: Bus;
	queue?: QueueController;
	volume?: VolumeController;
	filter?: FilterController;
	transition?: TransitionController;
	antiStuck?: AntiStuckController;
	stream?: StreamController;
	save?: SaveController;
	lifecycle?: LifecycleController;
	tts?: TTSController;
	search?: SearchController;
	forward?: ForwardController;
	resourceRefresh?: ResourceRefreshController;
	eventBridge?: PlayerEventBridge;
	plugin?: PluginController;
	extension?: ExtensionController;
	session?: PlaybackSessionController;
}
